language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coverage"
  - "python setup.py install"
script: nosetests
after_script:
  - nosetests --with-coverage --cover-package diff_cover
  - coverage xml
  - diff-cover coverage.xml