language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
  - "python setup.py install"
script:
  - git remote update
  - nosetests --with-coverage --cover-package=diff_cover
  - git remote update
  - coverage xml
  - diff-cover coverage.xml